//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinReportingSol.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public string PurchaseNo { get; set; }
        public System.DateTime TrDate { get; set; }
        public int VendorId { get; set; }
        public int SourceId { get; set; }
        public string Remarks { get; set; }
        public int BranchId { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public int ReceivedByID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Source Source { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
