//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinReportingSol.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public string Invoice { get; set; }
        public System.DateTime TrDate { get; set; }
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public string Remarks { get; set; }
        public int BranchId { get; set; }
        public string OrderNo { get; set; }
        public int PaymentTypeId { get; set; }
        public int SaleFrom { get; set; }
        public int SaleType { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
